#define CONFIG_DACB 8
#define CONFIG_DACA 0
#define CONFIG_BUFFERED_OUTPUT 4
#define CONFIG_STANDARD_OUTPUT 0
#define CONFIG_2X_GAIN 0
#define CONFIG_1X_GAIN 2
#define CONFIG_OUTPUT_ON 1
#define CONFIG_OUTPUT_HIGHZ 0